Pining Version for importlib-metadata venv fix
Error: 
  File "/usr/local/Caskroom/miniconda/base/envs/nameko-devex/lib/python3.7/site-packages/kombu/utils/compat.py", line 93, in entrypoints
    for ep in importlib_metadata.entry_points().get(namespace, [])
AttributeError: 'EntryPoints' object has no attribute 'get'
Latest version of importlib returns tuple instead of list
K8s fix will be separate